DROP TABLE IF EXISTS CONTROL_PANEL.MENU;

CREATE TABLE CONTROL_PANEL.MENU
(
    ID          BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    NAME        VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    MENU_ROUTE  VARCHAR NOT NULL,
    MODULE_ID   BIGINT  NOT NULL,
    IS_ACTIVE   INT
);