DROP TABLE IF EXISTS CONTROL_PANEL.MODULE;

CREATE TABLE CONTROL_PANEL.MODULE
(
    ID           BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    NAME         VARCHAR NOT NULL,
    DESCRIPTION  VARCHAR NOT NULL,
    IS_ACTIVE    INT     NOT NULL,
    MODULE_ROUTE VARCHAR NOT NULL
);
