codecov:
  require_ci_to_pass: yes
  branch: master
  max_report_age: 24h

coverage:
  precision: 2
  round: down
  range: "70...100"

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no