ALTER TABLE MASTER_DATA.DIMENSION_DIMENSION_PROPERTY
    ADD CONSTRAINT FK_DIMENSION_ID
        FOREIGN KEY (DIMENSION_ID)
            REFERENCES MASTER_DATA.DIMENSION (ID);
;

ALTER TABLE MASTER_DATA.DIMENSION_DIMENSION_PROPERTY
    ADD CONSTRAINT FK_DIMENSION_PROPERTY_ID
        FOREIGN KEY (DIMENSION_PROPERTY_ID)
            REFERENCES MASTER_DATA.DIMENSION_PROPERTY (ID);
;

ALTER TABLE MASTER_DATA.DIMENSION_DIMENSION_PROPERTY
    ADD CONSTRAINT FK_SORT_ORDER
        FOREIGN KEY (SORT_ORDER_ID)
            REFERENCES MASTER_DATA.SORT_ORDER (ID);

