# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 batch: false
 branches:
   include:
     - features/*
     - fixes/*
     - master
 paths:
   exclude:
     - README.md

pool: 'contabo'

variables:
  buildConfiguration: 'Release'
  buildNumber: '$(Build.BuildNumber)'

steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: 'src/DigitalLibrary.IaC.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: 'src/DigitalLibrary.IaC.sln'
- task: DotNetCoreCLI@2
  displayName: 'Test'
  inputs:
    command: 'test'
    projects: '**/*Tests.csproj'
- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: true

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo "Tagging Build: $buildNumber"
      
      git tag $buildNumber
      git push origin $buildNumber