# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pr:
- master

pool: 'contabo'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore command'
  inputs:
    command: 'restore'
    projects: 'src/DigitalLibrary.IaC.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build command'
  inputs:
    command: 'build'
    projects: 'src/DigitalLibrary.IaC.sln'
- task: DotNetCoreCLI@2
  displayName: 'dotnet test command'
  inputs:
    command: 'test'
    projects: 'src/DigitalLibrary.IaC.sln'