# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
    - master
  exclude:
    - doc/*
 paths:
     exclude:
         - src/README.md
         - src/doc/*

pr:
- master

pool: 'contabo'

steps:

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'src/DigitalLibrary.sln'
    arguments: 'Debug'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'src/DigitalLibrary.sln'
    arguments: '--logger trx \
                --results-directory "$(Agent.TempDirectory)/testresults/" \
                --no-build \
                /p:CollectCoverage=true \
                /p:p:CoverletOutput="./coverage/" \
                /p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute\" \
                /p:CoverletOutputFormat=opencover'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xunit'
    testResultsFiles: '$(Agent.TempDirectory)/testresults/*.trx'
    mergeTestResults: true

- script: |
    bash <(curl -s https://codecov.io/bash) -v
  displayName: 'Upload to Codecov.io'