# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
    exclude:
      - doc/*
  paths:
    exclude:
      - src/README.md
      - src/doc/*

schedules:
  - cron: "0 */12 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

pr:
  - master

pool: 'contabo'

steps:
  - script: dotnet tool uninstall JetBrains.dotCover.GlobalTool -g
    displayName: "Remove dotCover"

  - script: dotnet tool install JetBrains.dotCover.GlobalTool -g
    displayName: "Install dotCover"

  - task: DotNetCoreCLI@2
    displayName: 'Restoring...'
    inputs:
      command: 'restore'
      projects: 'src/DigitalLibrary.sln'
      feedsToUse: 'select'
      noCache: false

  - task: DotNetCoreCLI@2
    displayName: 'Building...'
    inputs:
      command: 'build'
      projects: 'src/DigitalLibrary.sln'
      arguments: '-c Debug'

  #  - script: |
  #      dotnet test src/DigitalLibrary.sln \
  #      --collect:"XPlat Code Coverage" \
  #      --settings coverage.runsettings \
  #      --no-build
  #    displayName: 'Coverage'

  - task: DotNetCoreCLI@2
    displayName: 'Testing and publish result...'
    inputs:
      command: 'test'
      projects: 'src/DigitalLibrary.sln'
      arguments: '--no-build'

  - script: |
      dotnet dotcover test --no-build --dcReportType=XML

  - script: |
      bash <(curl -s https://codecov.io/bash)
    displayName: "Codecov upload"