# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
    - master
  exclude:
    - doc/*
 paths:
     exclude:
         - src/README.md
         - src/doc/*

pr:
- master

pool: 'contabo'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore command'
  inputs:
    command: 'restore'
    projects: 'src/DigitalLibrary.sln'
    feedsToUse: 'select'
- task: DotNetCoreCLI@2
  displayName: 'dotnet build command'
  inputs:
    command: 'build'
    projects: 'src/DigitalLibrary.sln'

- script:

- task: DotNetCoreCLI@2
  displayName: 'dotnet test command'
  inputs:
    command: 'test'
    projects: 'src/DigitalLibrary.sln'
    #arguments: '/p:CollectCoverage=true /p:CoverletOutputFormat=cobertura /p:CoverletOutput=./coverage/'
    arguments: '/p:CollectCoverage=true 
                /p:CoverletOutputFormat=cobertura 
                /p:ExcludeByAttribute=ExcludeFromCodeCoverage'
    publishTestResults: true
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/src/**/coverage.cobertura.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/src/'
    failIfCoverageEmpty: true

- script: |
    bash <(curl -s https://codecov.io/bash) -v
  displayName: 'Upload to Codecov.io'
