# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  branches:
    include:
      - master
    exclude:
      - doc/*
  paths:
    exclude:
      - src/README.md
      - src/doc/*

schedules:
  - cron: "0 */12 * * *"
    displayName: Daily build
    branches:
      include:
        - master
    always: true

pr:
  - master

pool: 'contabo'

steps:
  - task: DotNetCoreCLI@2
    displayName: 'Restoring...'
    inputs:
      command: 'restore'
      projects: 'src/DigitalLibrary.sln'
      feedsToUse: 'select'
      noCache: false

  - task: DotNetCoreCLI@2
    displayName: 'Building...'
    inputs:
      command: 'build'
      projects: 'src/DigitalLibrary.sln'
      arguments: '-c Debug'

  - task: DotNetCoreCLI@2
    displayName: 'Testing and publish result...'
    inputs:
      command: 'test'
      projects: 'src/DigitalLibrary.sln'
      arguments: '--no-build'