# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

variables:
  solution: "src/DigitalLibrary.sln"

trigger:
 branches:
  include:
    - master
  exclude:
    - doc/*
 paths:
     exclude:
         - src/README.md
         - src/doc/*

pr:
- master

pool: 'contabo'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore command'
  inputs:
    command: 'restore'
    projects: 'src/DigitalLibrary.sln'
    feedsToUse: 'select'

- script: dotnet build $(solution) --configuration Debug
  displayName: 'Building...'

- script: |
    dotnet test --logger trx --no-build /p:CollectCoverage=true 
                /p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute\"
                /p:CoverletOutputFormat=opencover 
  displayName: 'Testing...'

- task: PublishTestResults@2
  inputs:
    testRunner: xunit
    testResultsFiles: '**/*.trx'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/src/**/coverage.cobertura.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/src/'
    failIfCoverageEmpty: true

- script: |
    bash <(curl -s https://codecov.io/bash) -v
  displayName: 'Upload to Codecov.io'