# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
 branches:
  include:
    - master
  exclude:
    - doc/*
 paths:
     exclude:
         - src/README.md
         - src/doc/*

pr:
- master

pool: 'contabo'

steps:
- script: dotnet restore $(solution)
  displayName: 'Restoring...'

- script: dotnet build $(solution) --configuration Debug
  displayName: 'Building...'

- script: |
    dotnet test --logger trx \
                --no-build \
                /p:CollectCoverage=true \
                /p:ExcludeByAttribute=\"Obsolete,GeneratedCodeAttribute,CompilerGeneratedAttribute\" \
                /p:CoverletOutputFormat=opencover \
                $(solution)
  displayName: 'Testing...'

- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'xunit'
    testResultsFiles: '**/*.trx'
    mergeTestResults: true

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(System.DefaultWorkingDirectory)/src/**/coverage.cobertura.xml'
    pathToSources: '$(System.DefaultWorkingDirectory)/src/'
    failIfCoverageEmpty: true

- script: |
    bash <(curl -s https://codecov.io/bash) -v
  displayName: 'Upload to Codecov.io'