coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 10%  # the leniency in hitting the target
        informational: true
    patch:
      default:
        target: 80%
        informational: true
comment:
  layout: "reach, diff, flags, files"
  behavior: default