coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 10%  # the leniency in hitting the target
        base: auto
    patch:
      default:
        target: 80%
        treshold: 10%
        base: auto
comment:
  layout: "reach, diff, flags, files"
  behavior: default