GRANT SELECT ON TABLE CONTROL_PANEL.MODULE TO DILIB_WEBAPI;
GRANT UPDATE ON TABLE CONTROL_PANEL.MODULE TO DILIB_WEBAPI;
GRANT DELETE ON TABLE CONTROL_PANEL.MODULE TO DILIB_WEBAPI;
GRANT INSERT ON TABLE CONTROL_PANEL.MODULE TO DILIB_WEBAPI;