ALTER TABLE TEAM_MANAGER.PEOPLE
    ADD CONSTRAINT FK_COMPANY_ID
        FOREIGN KEY (COMPANY_ID)
            REFERENCES TEAM_MANAGER.COMPANY (ID);

ALTER TABLE TEAM_MANAGER.PEOPLE
    ADD CONSTRAINT FK_POSITION_ID
        FOREIGN KEY (POSITION_ID)
            REFERENCES TEAM_MANAGER.POSITION (ID);

ALTER TABLE TEAM_MANAGER.PEOPLE
    ADD CONSTRAINT FK_TITLE_ID
        FOREIGN KEY (TITLE_ID)
            REFERENCES TEAM_MANAGER.TITLE (ID);
