DROP TABLE IF EXISTS TEAM_MANAGER.COMPANY;
CREATE TABLE TEAM_MANAGER.COMPANY
(
    ID          BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    NAME        VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    URL         VARCHAR NOT NULL,
    IS_ACTIVE   INT     NOT NULL DEFAULT 0
);