DROP TABLE IF EXISTS TEAM_MANAGER.EVENT;
CREATE TABLE TEAM_MANAGER.EVENT
(
    ID        BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    NAME      VARCHAR NOT NULL,
    IS_ACTIVE INT     NOT NULL DEFAULT 0
);