DROP TABLE IF EXISTS TEAM_MANAGER.PEOPLE_EVENT_LOG;
CREATE TABLE TEAM_MANAGER.PEOPLE_EVENT_LOG
(
    ID        BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    DETAILS   VARCHAR NOT NULL,
    IS_ACTIVE INT     NOT NULL DEFAULT 0,
    PEOPLE_ID BIGINT  NOT NULL,
    EVENT_ID  BIGINT  NOT NULL
);