DROP TABLE IF EXISTS TEAM_MANAGER.POSITION;
CREATE TABLE TEAM_MANAGER.POSITION
(
    ID        BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    NAME      VARCHAR NOT NULL,
    IS_ACTIVE INT     NOT NULL DEFAULT 0
);