DROP TABLE IF EXISTS TEAM_MANAGER.TITLE;
CREATE TABLE TEAM_MANAGER.TITLE
(
    ID        BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    NAME      VARCHAR NOT NULL,
    IS_ACTIVE INT     NOT NULL DEFAULT 0
);