DROP TABLE IF EXISTS MASTER_DATA.DIMENSION_PROPERTY
;

CREATE TABLE MASTER_DATA.DIMENSION_PROPERTY
(
  ID        BIGINT  GENERATED ALWAYS AS IDENTITY UNIQUE ,
  NAME      VARCHAR NOT NULL,
  IS_ACTIVE INT
)
;