DROP TABLE IF EXISTS MASTER_DATA.DIMENSION
;

CREATE TABLE MASTER_DATA.DIMENSION
(
    ID        BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE,
    NAME      VARCHAR NOT NULL,
    IS_ACTIVE INT     NOT NULL DEFAULT 0
)
;