DROP TABLE IF EXISTS MASTER_DATA.DIMENSION_DIMENSION_PROPERTY
;

CREATE TABLE MASTER_DATA.DIMENSION_DIMENSION_PROPERTY
(
  ID                    BIGINT GENERATED ALWAYS AS IDENTITY UNIQUE ,
  DIMENSION_ID          BIGINT NOT NULL,
  DIMENSION_PROPERTY_ID BIGINT NOT NULL,
  SORT_ORDER_ID         BIGINT NOT NULL
)
;